// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/wasm/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Message type to push new wasm code
type MsgPushNewWasmCode struct {
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Code   []byte `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (m *MsgPushNewWasmCode) Reset()         { *m = MsgPushNewWasmCode{} }
func (m *MsgPushNewWasmCode) String() string { return proto.CompactTextString(m) }
func (*MsgPushNewWasmCode) ProtoMessage()    {}
func (*MsgPushNewWasmCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d9737363bf1e38d, []int{0}
}
func (m *MsgPushNewWasmCode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPushNewWasmCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPushNewWasmCode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPushNewWasmCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPushNewWasmCode.Merge(m, src)
}
func (m *MsgPushNewWasmCode) XXX_Size() int {
	return m.Size()
}
func (m *MsgPushNewWasmCode) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPushNewWasmCode.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPushNewWasmCode proto.InternalMessageInfo

func (m *MsgPushNewWasmCode) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgPushNewWasmCode) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

// Response in case of successful handling
type MsgPushNewWasmCodeResponse struct {
	CodeId []byte `protobuf:"bytes,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
}

func (m *MsgPushNewWasmCodeResponse) Reset()         { *m = MsgPushNewWasmCodeResponse{} }
func (m *MsgPushNewWasmCodeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPushNewWasmCodeResponse) ProtoMessage()    {}
func (*MsgPushNewWasmCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d9737363bf1e38d, []int{1}
}
func (m *MsgPushNewWasmCodeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPushNewWasmCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPushNewWasmCodeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPushNewWasmCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPushNewWasmCodeResponse.Merge(m, src)
}
func (m *MsgPushNewWasmCodeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPushNewWasmCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPushNewWasmCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPushNewWasmCodeResponse proto.InternalMessageInfo

func (m *MsgPushNewWasmCodeResponse) GetCodeId() []byte {
	if m != nil {
		return m.CodeId
	}
	return nil
}

// Message type to update wasm code id
type MsgUpdateWasmCodeId struct {
	Signer   string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CodeId   []byte `protobuf:"bytes,3,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
}

func (m *MsgUpdateWasmCodeId) Reset()         { *m = MsgUpdateWasmCodeId{} }
func (m *MsgUpdateWasmCodeId) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateWasmCodeId) ProtoMessage()    {}
func (*MsgUpdateWasmCodeId) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d9737363bf1e38d, []int{2}
}
func (m *MsgUpdateWasmCodeId) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateWasmCodeId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateWasmCodeId.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateWasmCodeId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateWasmCodeId.Merge(m, src)
}
func (m *MsgUpdateWasmCodeId) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateWasmCodeId) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateWasmCodeId.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateWasmCodeId proto.InternalMessageInfo

func (m *MsgUpdateWasmCodeId) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgUpdateWasmCodeId) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *MsgUpdateWasmCodeId) GetCodeId() []byte {
	if m != nil {
		return m.CodeId
	}
	return nil
}

// Response in case of successful handling
type MsgUpdateWasmCodeIdResponse struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CodeId   []byte `protobuf:"bytes,2,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
}

func (m *MsgUpdateWasmCodeIdResponse) Reset()         { *m = MsgUpdateWasmCodeIdResponse{} }
func (m *MsgUpdateWasmCodeIdResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateWasmCodeIdResponse) ProtoMessage()    {}
func (*MsgUpdateWasmCodeIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d9737363bf1e38d, []int{3}
}
func (m *MsgUpdateWasmCodeIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateWasmCodeIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateWasmCodeIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateWasmCodeIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateWasmCodeIdResponse.Merge(m, src)
}
func (m *MsgUpdateWasmCodeIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateWasmCodeIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateWasmCodeIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateWasmCodeIdResponse proto.InternalMessageInfo

func (m *MsgUpdateWasmCodeIdResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *MsgUpdateWasmCodeIdResponse) GetCodeId() []byte {
	if m != nil {
		return m.CodeId
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgPushNewWasmCode)(nil), "ibc.lightclients.wasm.v1.MsgPushNewWasmCode")
	proto.RegisterType((*MsgPushNewWasmCodeResponse)(nil), "ibc.lightclients.wasm.v1.MsgPushNewWasmCodeResponse")
	proto.RegisterType((*MsgUpdateWasmCodeId)(nil), "ibc.lightclients.wasm.v1.MsgUpdateWasmCodeId")
	proto.RegisterType((*MsgUpdateWasmCodeIdResponse)(nil), "ibc.lightclients.wasm.v1.MsgUpdateWasmCodeIdResponse")
}

func init() { proto.RegisterFile("ibc/lightclients/wasm/v1/tx.proto", fileDescriptor_1d9737363bf1e38d) }

var fileDescriptor_1d9737363bf1e38d = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4e, 0x2a, 0x31,
	0x18, 0xc5, 0x29, 0xdc, 0x70, 0x2f, 0x0d, 0xc9, 0x35, 0x35, 0x51, 0x02, 0xc9, 0x04, 0x59, 0xb1,
	0x70, 0x5a, 0x51, 0x89, 0xee, 0x34, 0xba, 0x62, 0x81, 0x31, 0x63, 0x8c, 0xd1, 0x8d, 0x61, 0xda,
	0xa6, 0x34, 0x61, 0xe8, 0x84, 0xaf, 0x03, 0xf8, 0x16, 0x3e, 0x96, 0x4b, 0x96, 0x2e, 0x0d, 0xbc,
	0x83, 0x6b, 0x33, 0x83, 0x10, 0xfe, 0x88, 0x09, 0xbb, 0x7e, 0xed, 0xe9, 0xef, 0x7c, 0x39, 0x39,
	0xf8, 0x40, 0xfb, 0x9c, 0x75, 0xb4, 0x6a, 0x5b, 0xde, 0xd1, 0xb2, 0x6b, 0x81, 0x0d, 0x5a, 0x10,
	0xb0, 0x7e, 0x8d, 0xd9, 0x21, 0x0d, 0x7b, 0xc6, 0x1a, 0x52, 0xd0, 0x3e, 0xa7, 0x8b, 0x12, 0x1a,
	0x4b, 0x68, 0xbf, 0x56, 0xb9, 0xc4, 0xa4, 0x09, 0xea, 0x36, 0x82, 0xf6, 0x8d, 0x1c, 0x3c, 0xb4,
	0x20, 0xb8, 0x36, 0x42, 0x92, 0x3d, 0x9c, 0x05, 0xad, 0xba, 0xb2, 0x57, 0x40, 0x65, 0x54, 0xcd,
	0x79, 0xdf, 0x13, 0x21, 0xf8, 0x0f, 0x37, 0x42, 0x16, 0xd2, 0x65, 0x54, 0xcd, 0x7b, 0xc9, 0xb9,
	0x52, 0xc7, 0xc5, 0x75, 0x82, 0x27, 0x21, 0x34, 0x5d, 0x90, 0x64, 0x1f, 0xff, 0x8d, 0x55, 0xcf,
	0x5a, 0x24, 0xa8, 0xbc, 0x97, 0x8d, 0xc7, 0x86, 0xa8, 0x70, 0xbc, 0xdb, 0x04, 0x75, 0x1f, 0x8a,
	0x96, 0x95, 0xb3, 0x5f, 0x0d, 0xb1, 0xd1, 0xb9, 0x84, 0x73, 0xd3, 0xd5, 0x63, 0x52, 0x3a, 0x79,
	0xfa, 0x37, 0xbd, 0x68, 0x88, 0x45, 0x93, 0xcc, 0x92, 0xc9, 0x1d, 0x2e, 0xfd, 0x60, 0x32, 0x5f,
	0x6e, 0x09, 0x8a, 0x36, 0x43, 0xd3, 0x8b, 0xd0, 0xe3, 0x4f, 0x84, 0x33, 0x4d, 0x50, 0x24, 0xc2,
	0xff, 0x57, 0x73, 0x3b, 0xa4, 0x9b, 0x82, 0xa6, 0xeb, 0x19, 0x15, 0x4f, 0xb7, 0x51, 0xcf, 0x97,
	0x1e, 0xe2, 0x9d, 0xb5, 0xd4, 0xdc, 0x5f, 0x49, 0xab, 0xf2, 0x62, 0x7d, 0x2b, 0xf9, 0xcc, 0xf9,
	0xea, 0xf1, 0x6d, 0xec, 0xa0, 0xd1, 0xd8, 0x41, 0x1f, 0x63, 0x07, 0xbd, 0x4e, 0x9c, 0xd4, 0x68,
	0xe2, 0xa4, 0xde, 0x27, 0x4e, 0xea, 0xe9, 0x42, 0x69, 0xdb, 0x8e, 0x7c, 0xca, 0x4d, 0xc0, 0xb8,
	0x81, 0xc0, 0x00, 0xd3, 0x3e, 0x77, 0x95, 0x61, 0xfd, 0x33, 0x16, 0x18, 0x11, 0x75, 0x24, 0x4c,
	0x2b, 0xea, 0xce, 0x3a, 0x7a, 0x74, 0xee, 0x26, 0x35, 0xb5, 0x2f, 0xa1, 0x04, 0x3f, 0x9b, 0xf4,
	0xf4, 0xe4, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x41, 0x45, 0x75, 0xcc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// PushNewWasmCode defines a rpc handler method for PushNewWasmCode.
	PushNewWasmCode(ctx context.Context, in *MsgPushNewWasmCode, opts ...grpc.CallOption) (*MsgPushNewWasmCodeResponse, error)
	// UpdateWasmCodeId defines a rpc handler method for UpdateWasmCodeId.
	UpdateWasmCodeId(ctx context.Context, in *MsgUpdateWasmCodeId, opts ...grpc.CallOption) (*MsgUpdateWasmCodeIdResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) PushNewWasmCode(ctx context.Context, in *MsgPushNewWasmCode, opts ...grpc.CallOption) (*MsgPushNewWasmCodeResponse, error) {
	out := new(MsgPushNewWasmCodeResponse)
	err := c.cc.Invoke(ctx, "/ibc.lightclients.wasm.v1.Msg/PushNewWasmCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateWasmCodeId(ctx context.Context, in *MsgUpdateWasmCodeId, opts ...grpc.CallOption) (*MsgUpdateWasmCodeIdResponse, error) {
	out := new(MsgUpdateWasmCodeIdResponse)
	err := c.cc.Invoke(ctx, "/ibc.lightclients.wasm.v1.Msg/UpdateWasmCodeId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// PushNewWasmCode defines a rpc handler method for PushNewWasmCode.
	PushNewWasmCode(context.Context, *MsgPushNewWasmCode) (*MsgPushNewWasmCodeResponse, error)
	// UpdateWasmCodeId defines a rpc handler method for UpdateWasmCodeId.
	UpdateWasmCodeId(context.Context, *MsgUpdateWasmCodeId) (*MsgUpdateWasmCodeIdResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) PushNewWasmCode(ctx context.Context, req *MsgPushNewWasmCode) (*MsgPushNewWasmCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushNewWasmCode not implemented")
}
func (*UnimplementedMsgServer) UpdateWasmCodeId(ctx context.Context, req *MsgUpdateWasmCodeId) (*MsgUpdateWasmCodeIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWasmCodeId not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_PushNewWasmCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPushNewWasmCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PushNewWasmCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ibc.lightclients.wasm.v1.Msg/PushNewWasmCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PushNewWasmCode(ctx, req.(*MsgPushNewWasmCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateWasmCodeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateWasmCodeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateWasmCodeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ibc.lightclients.wasm.v1.Msg/UpdateWasmCodeId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateWasmCodeId(ctx, req.(*MsgUpdateWasmCodeId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.lightclients.wasm.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushNewWasmCode",
			Handler:    _Msg_PushNewWasmCode_Handler,
		},
		{
			MethodName: "UpdateWasmCodeId",
			Handler:    _Msg_UpdateWasmCodeId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/lightclients/wasm/v1/tx.proto",
}

func (m *MsgPushNewWasmCode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPushNewWasmCode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPushNewWasmCode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Code) > 0 {
		i -= len(m.Code)
		copy(dAtA[i:], m.Code)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Code)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPushNewWasmCodeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPushNewWasmCodeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPushNewWasmCodeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CodeId) > 0 {
		i -= len(m.CodeId)
		copy(dAtA[i:], m.CodeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CodeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateWasmCodeId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateWasmCodeId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateWasmCodeId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CodeId) > 0 {
		i -= len(m.CodeId)
		copy(dAtA[i:], m.CodeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CodeId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateWasmCodeIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateWasmCodeIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateWasmCodeIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CodeId) > 0 {
		i -= len(m.CodeId)
		copy(dAtA[i:], m.CodeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CodeId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgPushNewWasmCode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Code)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPushNewWasmCodeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CodeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateWasmCodeId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CodeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateWasmCodeIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CodeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgPushNewWasmCode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPushNewWasmCode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPushNewWasmCode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Code = append(m.Code[:0], dAtA[iNdEx:postIndex]...)
			if m.Code == nil {
				m.Code = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPushNewWasmCodeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPushNewWasmCodeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPushNewWasmCodeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeId = append(m.CodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.CodeId == nil {
				m.CodeId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateWasmCodeId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateWasmCodeId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateWasmCodeId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeId = append(m.CodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.CodeId == nil {
				m.CodeId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateWasmCodeIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateWasmCodeIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateWasmCodeIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeId = append(m.CodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.CodeId == nil {
				m.CodeId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
